Repository meilisearch/meilisearch-rust, pull requests merged in 2020-10, with the labels that each got.

#52 Add Bors
  .github/workflows/rust.yml
  CONTRIBUTING.md
  bors.toml
Labels: skip-changelog

#50 Changes about the MeiliSearch's next release (v0.15.0)
  README.md
  README.tpl
Labels: skip-changelog

#46 Improve Query and SearchResults
  Cargo.toml
  README.md
  src/indexes.rs
  src/lib.rs
  src/search.rs
  src/settings.rs
Labels: Hacktoberfest, breaking-change

#40 Add code-sample file
  .code-samples.meilisearch.yaml
Labels: Hacktoberfest, skip-changelog

#60 Update README
  README.md
  README.tpl
Labels: skip-changelog
