Repository meilisearch/meilisearch-rust, pull requests merged in 2022-09, with the labels that each got.

#333 Update search params for v0.29.0
  src/search.rs
Labels: enhancement

#330 Fix wasm panic when trying to change the user-agent
  CONTRIBUTING.md
  examples/web_app/README.md
  examples/web_app/src/lib.rs
  src/request.rs
Labels: bug

#335 Update version for the next release (v0.18.1)
  Cargo.toml
  README.md
  README.tpl
Labels: skip-changelog

#338 Remove Arc on api_key and host in Client structure
  src/client.rs
Labels: breaking-change

#339 Update version for the next release (v.19.0)
  .code-samples.meilisearch.yaml
  Cargo.toml
  README.md
  README.tpl
Labels: skip-changelog

#341 Replace struct Query with SearchQuery
  .code-samples.meilisearch.yaml
  src/indexes.rs
  src/lib.rs
  src/search.rs
Labels: breaking-change
