Repository meilisearch/meilisearch-rust, pull requests merged in 2022-10, with the labels that each got.

#344 Add faceting index settings methods
  .code-samples.meilisearch.yaml
  src/settings.rs
Labels: enhancement

#347 feat: Add `with_array_filter()` function to allow passing array as a filter list
  Cargo.toml
  src/search.rs
Labels: enhancement

#349 Update version for the next release (v0.20.1)
  .github/ISSUE_TEMPLATE/bug_report.md
  Cargo.toml
  README.md
  README.tpl
Labels: skip-changelog

#355 Fix indentation of `authorization_header_1` code sample
  .code-samples.meilisearch.yaml
Labels: documentation

#357 Add cargo fmt in contributing and correctly in CI
  .github/workflows/tests.yml
  CONTRIBUTING.md
Labels: skip-changelog

#356 Improves error handling by using `thiserror` lib
  Cargo.toml
  src/errors.rs
Labels: skip-changelog, maintenance

#362 Adds samples for matching stragegy
  .code-samples.meilisearch.yaml
Labels: documentation, skip-changelog

#359 Checks that all error messages are correctly parsed
  src/errors.rs
Labels: skip-changelog
