Repository meilisearch/meilisearch-rust, pull requests merged in 2022-02, with the labels that each got.

#227 Api key
  src/client.rs
  src/errors.rs
  src/key.rs
  src/lib.rs
  src/request.rs
Labels: breaking-change

#228 Update docs according to v0.25.0
  .code-samples.meilisearch.yaml
  README.md
  meilisearch-test-macro/README.md
  src/lib.rs
Labels: skip-changelog

#235 Refactorise the settings
  src/settings.rs
  src/tasks.rs
Labels: enhancement

#234 Refactorise the errors
  src/client.rs
  src/errors.rs
  src/request.rs
  src/tasks.rs
Labels: breaking-change

#237 Put type on timestamp and duration
  .code-samples.meilisearch.yaml
  Cargo.toml
  src/client.rs
  src/indexes.rs
  src/key.rs
  src/tasks.rs
Labels: breaking-change

#243 Update version for the next release (v0.15.0)
  .code-samples.meilisearch.yaml
  Cargo.toml
  README.md
  README.tpl
Labels: skip-changelog
