Repository meilisearch/meilisearch-rust, pull requests merged in 2022-11, with the labels that each got.

#376 Fix primary key test using the wrong index name
  src/indexes.rs
Labels: skip-changelog, maintenance

#371 Fix skip-changelog tag in dependabot file
  .github/dependabot.yml
Labels: skip-changelog

#358 Adds `Document` proc macro for easy index configuration
  Cargo.toml
  meilisearch-index-setting-macro/Cargo.toml
  meilisearch-index-setting-macro/src/lib.rs
  src/documents.rs
  src/lib.rs
Labels: enhancement

#383 Fix path to `meilisearch_sdk` in Document derive proc macro
  Cargo.toml
  meilisearch-index-setting-macro/Cargo.toml
  meilisearch-index-setting-macro/src/lib.rs
  src/documents.rs
  src/lib.rs
Labels: skip-changelog

#389 Add snapshot_creation task type for v0.30.0
  src/tasks.rs
Labels: enhancement

#384 Add missing_master_key error code for v0.30.0
  src/errors.rs
  src/tasks.rs
Labels: skip-changelog

#390 Add `error` field in all types of task status for v0.30.0
  src/tasks.rs
Labels: breaking-change

#382 Add swap indexes for v0.30.0
  src/client.rs
  src/tasks.rs
Labels: enhancement

#377 Add cancel task for v0.30.0
  .code-samples.meilisearch.yaml
  src/client.rs
  src/indexes.rs
  src/tasks.rs
Labels: breaking-change

#391 Uses big_S to cleanup tests
  Cargo.toml
  src/client.rs
  src/documents.rs
  src/indexes.rs
  src/search.rs
  src/task_info.rs
  src/tasks.rs
  src/tenant_tokens.rs
Labels: skip-changelog

#393 Add provided_ids detail setting for v0.30.0
  src/tasks.rs
Labels: enhancement

#392 Rename setting detail original filters to original filter for v0.30.0
  src/tasks.rs
Labels: skip-changelog

#398 Add canceled by task filter for v0.30.0
  src/tasks.rs
Labels: skip-changelog

#399 Update version for the next release (v0.21.0)
  .code-samples.meilisearch.yaml
  Cargo.toml
  README.md
  README.tpl
Labels: skip-changelog
