Repository meilisearch/meilisearch-rust, pull requests merged in 2022-04, with the labels that each got.

#256 Add code samples
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#267 fixed formatting with clippy and removed Document trait
  .code-samples.meilisearch.yaml
  README.md
  examples/web_app/src/document.rs
  src/client.rs
  src/document.rs
  src/indexes.rs
  src/lib.rs
  src/request.rs
  src/search.rs
  src/settings.rs
  src/tasks.rs
Labels: breaking-change

#262 Add methods to automatically add/update documents in batches
  src/indexes.rs
Labels: enhancement

#269 Delete index before creation in test macro
  meilisearch-test-macro/src/lib.rs
Labels: skip-changelog

#263 Feature/Tenant Token
  Cargo.toml
  src/client.rs
  src/errors.rs
  src/lib.rs
  src/search.rs
  src/tenant_tokens.rs
Labels: enhancement

#270 Fix cropping tests failing due to changes in v0.27
  src/search.rs
Labels: breaking-change

#271 Add missing IndexUpdate task type
  src/tasks.rs
Labels: bug

#272 Update version for the next release (v0.16.0)
  .code-samples.meilisearch.yaml
  Cargo.toml
  README.md
  README.tpl
Labels: skip-changelog

#277 Update the code samples with highlighting and crop parameters
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#274 Add new search parameters highlightPreTag, highlightPostTag and cropMarker
  src/search.rs
Labels: enhancement
