Repository meilisearch/meilisearch-rust, pull requests merged in 2022-05, with the labels that each got.

#279 initial commit for cli-app example to meilisearch-rust
  examples/cli-app/Cargo.toml
  examples/cli-app/assets/clothes.json
  examples/cli-app/src/main.rs
Labels: enhancement

#278 Remove jsonindex
  src/client.rs
  src/indexes.rs
Labels: breaking-change

#285 Improve the error message in case an unwrap happens in the test macro
  meilisearch-test-macro/src/lib.rs
Labels: skip-changelog, maintenance

#284 Remove an useless test.
  src/client.rs
  src/indexes.rs
Labels: skip-changelog, maintenance

#283 Improve the test-macro
  meilisearch-test-macro/src/lib.rs
Labels: bug, skip-changelog, maintenance

#286 Remove the wasm lib.rs from the manifest
  .github/workflows/tests.yml
  Cargo.toml
  examples/cli-app/src/main.rs
Labels: skip-changelog, maintenance

#254 Feature/Analytics
  Cargo.toml
  src/client.rs
  src/request.rs
Labels: enhancement

#287 Update version for the next release (v0.17.0)
  Cargo.toml
  README.md
  README.tpl
Labels: skip-changelog

#288 Add the new version to code-samples
  .code-samples.meilisearch.yaml
Labels: skip-changelog
