Repository meilisearch/meilisearch-rust, pull requests merged in 2023-05, with the labels that each got.

#470 refactor: use iterator instead for-loop
  src/search.rs
Labels: skip-changelog

#469 Add feature isahc-static-ssl
  Cargo.toml
  src/task_info.rs
Labels: enhancement

#466 Add Debug and Clone to all public API structs, and some CS
  examples/settings.rs
  examples/web_app/src/lib.rs
  src/client.rs
  src/dumps.rs
  src/indexes.rs
  src/key.rs
  src/lib.rs
  src/request.rs
  src/search.rs
  src/settings.rs
  src/task_info.rs
  src/tasks.rs
  src/tenant_tokens.rs
Labels: enhancement

#478 Fix json serialization error if meilisearch response contains facet_stats
  src/search.rs
Labels: bug
