Repository meilisearch/meilisearch-rust, pull requests merged in 2024-04, with the labels that each got.

#459 Feat trait to make clients customizable
  .github/workflows/tests.yml
  Cargo.toml
  README.md
  examples/cli-app-with-reqwest/Cargo.toml
  examples/cli-app-with-reqwest/assets/clothes.json
  examples/cli-app-with-reqwest/src/main.rs
  examples/cli-app/src/main.rs
  examples/settings.rs
  examples/web_app/src/lib.rs
  meilisearch-index-setting-macro/src/lib.rs
  meilisearch-test-macro/src/lib.rs
  src/client.rs
  src/documents.rs
  src/dumps.rs
  src/errors.rs
  src/features.rs
  src/indexes.rs
  src/key.rs
  src/lib.rs
  src/request.rs
  src/search.rs
  src/settings.rs
  src/task_info.rs
  src/tasks.rs
  src/tenant_tokens.rs
Labels: enhancement, breaking-change

#563 Use reqwest by default
  Cargo.toml
  README.md
  examples/cli-app-with-awc/Cargo.toml
  examples/cli-app-with-awc/assets/clothes.json
  examples/cli-app-with-awc/src/main.rs
  examples/cli-app-with-reqwest/src/main.rs
  examples/cli-app/Cargo.toml
  examples/cli-app/src/main.rs
  examples/settings.rs
  examples/web_app/src/lib.rs
  meilisearch-index-setting-macro/src/lib.rs
  meilisearch-test-macro/src/lib.rs
  src/client.rs
  src/documents.rs
  src/dumps.rs
  src/errors.rs
  src/features.rs
  src/indexes.rs
  src/key.rs
  src/lib.rs
  src/request.rs
  src/reqwest.rs
  src/search.rs
  src/settings.rs
  src/task_info.rs
  src/tasks.rs
  src/tenant_tokens.rs
  src/utils.rs
Labels: breaking-change

#571 Make the error type implement Send + Sync + 'static
  examples/cli-app-with-awc/Cargo.toml
  examples/cli-app-with-awc/src/main.rs
  src/errors.rs
Labels: enhancement

#572 created new snapshot method - fixes #537
  .code-samples.meilisearch.yaml
  src/lib.rs
  src/snapshots.rs
Labels: enhancement

#576 with_distrinct_attribute accepts None
  .code-samples.meilisearch.yaml
  meilisearch-index-setting-macro/src/lib.rs
  src/settings.rs
Labels: enhancement, breaking-change
