Repository meilisearch/meilisearch-rust, pull requests merged in 2025-07, with the labels that each got.

#674 Add support for similar docs query
  .github/workflows/tests.yml
  src/documents.rs
  src/indexes.rs
  src/lib.rs
  src/search.rs
  src/similar.rs
Labels: enhancement

#682 Merge dev into main
  .code-samples.meilisearch.yaml
  .github/workflows/tests.yml
  Cargo.toml
  README.md
  README.tpl
  meilisearch-index-setting-macro/Cargo.toml
  meilisearch-test-macro/Cargo.toml
  meilisearch-test-macro/README.md
  meilisearch-test-macro/src/lib.rs
  src/client.rs
  src/documents.rs
  src/features.rs
  src/indexes.rs
  src/key.rs
  src/lib.rs
  src/request.rs
  src/search.rs
  src/settings.rs
  src/similar.rs
  src/tasks.rs
Labels: breaking-change

#685 Adapt script to update macro version
  .github/scripts/check-release.sh
  scripts/update_macro_versions.sh
Labels: maintenance

#686 Fix release
  .github/scripts/check-release.sh
  Cargo.toml
  scripts/update_macro_versions.sh
Labels: maintenance

#688 Lighten `futures` dependency
  Cargo.toml
  src/request.rs
  src/reqwest.rs
  src/utils.rs
Labels: skip-changelog
